### ISSUE TITLE
Stats page display error

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#1866]
![fireshot screen capture 148 - my community - statistics center - localhost_smf2_1_index_php_action stats](https://cloud.githubusercontent.com/assets/431799/3350386/f5fb05e4-f9a9-11e3-954e-d88219262b6e.png)

This is in Firefox ofc.

**Comment by XinYenFon** [comment]
You need to write an alternate class for this, and use clear_left/right classes. You need to use alternate because of IE8 compatibility, otherwise just use CSS3 odd/even.

``` CSS
#statistics .half_content:nth-child(odd) {
    clear: right;
}
#statistics .half_content:nth-child(even) {
    clear: left;
}
#statistics .half_content.nobb {
    clear: none;
}
```
