### ISSUE TITLE
Scrutinizer configuration

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4222]
Scrutinizer is used here but improperly setup, therefore a lot of bogus issues exist. I propose we change the config to the following:

```
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

filter:
    excluded_paths:
        - '*.min.js'
        - 'Sources/minify/*'
        - 'Sources/ReCaptcha/*'

checks:
    php:
        variable_existence: true
        use_statement_alias_conflict: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        switch_fallthrough_commented: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        remove_extra_empty_lines: true
        property_assignments: true
        prefer_while_loop_over_for_loop: true
        precedence_mistakes: true
        precedence_in_conditions: true
        php5_style_constructor: true
        parse_doc_comments: true
        parameter_non_unique: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        optional_parameters_at_the_end: true
        no_unnecessary_if: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_trailing_whitespace: true
        no_short_open_tag: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        no_short_method_names:
            minimum: '3'
        no_goto: true
        no_global_keyword: true
        no_error_suppression: true
        no_empty_statements: true
        no_duplicate_arguments: true
        no_debug_code: true
        no_commented_out_code: true
        more_specific_types_in_doc_comments: true
        missing_arguments: true
        method_calls_on_non_object: true
        instanceof_class_exists: true
        foreach_traversable: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_line_ending: true
        fix_doc_comments: true
        encourage_single_quotes: true
        encourage_shallow_comparison: true
        encourage_postdec_operator: true
        duplication: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        catch_class_exists: true
        avoid_useless_overridden_methods: true
        avoid_usage_of_logical_operators: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true
        avoid_closing_tag: false
        avoid_aliased_php_functions: true
        assignment_of_null_return: true
        argument_type_checks: true
        avoid_todo_comments: true
        avoid_fixme_comments: true
        no_long_variable_names:
            maximum: '40'
        no_short_variable_names:
            minimum: '3'
        line_length:
            max_length: '150'
        phpunit_assertions: true
        remove_php_closing_tag: false
        one_class_per_file: false
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: false
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
```
